# Use an official Node.js runtime as a parent image
FROM node:16

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install client dependencies with the --legacy-peer-deps flag
RUN npm install --legacy-peer-deps

# Copy the client application files to the container
COPY . ./

# Expose the port the client runs on
EXPOSE 3000

# Start the React app
CMD ["npm", "start"]
