# Use an official Node.js runtime as a parent image
FROM node:16

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install server dependencies
RUN npm install

# Copy the server application files to the container
COPY . ./

# Expose the port the server runs on
EXPOSE 3001

# Start the Express server using nodemon
CMD ["npm", "start"]
